apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-secrets-controller
  labels:
    app.kubernetes.io/name: sync-secrets-controller
    app.kubernetes.io/part-of: sync-secrets-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sync-secrets-controller
  labels:
    app.kubernetes.io/name: sync-secrets-controller
    app.kubernetes.io/part-of: sync-secrets-controller
rules:
- apiGroups: [""]
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sync-secrets-clusterrole-controller-binding
  labels:
    app.kubernetes.io/name: sync-secrets-controller
    app.kubernetes.io/part-of: sync-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sync-secrets-controller
subjects:
  - kind: ServiceAccount
    name: sync-secrets-controller
    namespace: default