style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/xunleii/sync-secrets-operator
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refact
        - test
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refact: Code Refactoring
      test: Code Testing
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE