name: Go
on: [pull_request]
jobs:
  go-build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - run: go mod download
    - run: go build ./cmd/controller
  go-test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - run: go mod download
    - run: go test -v ./...
  go-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Download GolangCI-Lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
    - name: Run golangci-lint run
      run: $(go env GOPATH)/bin/golangci-lint run --verbose --timeout 5m
