name: Go - Test & Lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go build
    steps:
    - uses: actions/checkout@v2
    - name: Setup go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run: make build
  test:
    runs-on: ubuntu-latest
    name: Go test
    steps:
    - uses: actions/checkout@v2
    - name: Setup go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run: make test
  lint:
    runs-on: ubuntu-latest
    name: Go lint
    steps:
    - uses: actions/checkout@v2
    - name: Setup go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run: make lint
