name: GoReleaser
on:
  push:
    tags:
    - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: azure/docker-login@v1
      with:
        login-server: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: v0.129.0
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        GH_BRANCH: ${{ github.ref }}
        GH_USER: ${{ github.actor }}
        GH_HOST: github_action
    - name: Release docker manifests
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        export FULL_TAG=${GITHUB_REF##*/}
        docker manifest create quay.io/klst.pw/sync-secrets-operator:${FULL_TAG} \
          quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}-linux_armv7 \
          quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}-linux_arm64 \
          quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}-linux_amd64
        docker manifest create quay.io/klst.pw/sync-secrets-operator:${FULL_TAG%.*} \
          quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}-linux_armv7 \
          quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}-linux_arm64 \
          quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}-linux_amd64
        docker manifest create quay.io/klst.pw/sync-secrets-operator:${FULL_TAG%.*.*} \
          quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}-linux_armv7 \
          quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}-linux_arm64 \
          quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}-linux_amd64

        docker manifest push quay.io/klst.pw/sync-secrets-operator:${FULL_TAG}
        docker manifest push quay.io/klst.pw/sync-secrets-operator:${FULL_TAG%.*}
        docker manifest push quay.io/klst.pw/sync-secrets-operator:${FULL_TAG%.*.*}
